language: android
jdk: oraclejdk8

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

env:
  global:
    - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
    - ANDROID_SDKS=android-14
    - ANDROID_TARGET=android-14

before_install:
  # TODO: Remove the following line when Travis' platform-tools are updated to v25+
  - echo yes | android update sdk -a --filter platform-tools --no-ui --force

before_script:
  - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew connectedAndroidTest
  - ./gradlew assembleDebug assembleRelease
  - ./gradlew lint || (grep -A20 -B2 'severity="Error"' */build/outputs/*.xml; exit 1)
